name: ej1-workflow

on:
  push:
    branches:
      - main

jobs:
  tareas: 
    runs-on: ubuntu-latest
    steps: 
      - name: Descargar el codigo
        uses: actions/checkout@v4

      - name: Configurar entorno Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Ejecutar comandos
        run: |
             npm i
             npm test

      - name: Build imagen Dockerfile
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: app/Dockerfile
